name: Docker Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/landing:latest

      - name: Trigger DigitalOcean App Platform deployment
        env:
          DIGITALOCEAN_APP_PLATFORM_API_KEY: ${{secrets.DIGITALOCEAN_APP_PLATFORM_API_KEY}}
          DIGITALOCEAN_APP_PLATFORM_APP_ID: ${{vars.DIGITALOCEAN_APP_PLATFORM_APP_ID}}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $DIGITALOCEAN_APP_PLATFORM_API_KEY" \
            "https://api.digitalocean.com/v2/apps/$DIGITALOCEAN_APP_PLATFORM_APP_ID/deployments"
